name: sphinx-doctest

on:
  push: 
    branches:
      - main
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r doc/requirements.txt
    - name : Build package
      run: |
        pip install .  # include all extra dependencies
    - name: Build documentation
      # building html is necessary to include the module docstrings with autodoc
      run: |
        python -m sphinx -b html ./doc ./doc/sphinx_build
    - name: Run doctests
      # building html is necessary to include the module docstrings with autodoc
      run: |
        python -m sphinx -b doctest ./doc ./doc/sphinx_build
