name: Upload Python Package to test.pypi

on:
  # when a release is created
  release:
    types: [created]
  
  # when a tagged commit is pushed to *any* branch
  push:
    tags:
      - '**'  # on any tag

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'  # use minimum version that we support
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel build
    - name: Build
      run: python -m build .
    - name: Install for test
      run: python -m pip install .
    - name: quicktest
      run: |
        python -m pip install pytest
        pytest -m "not slow"
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
